"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG')
if os.environ.get('DEBUGMODE') == 'True':
    DEBUG = (os.environ.get('DEBUGMODE') == 'True')
else:
    DEBUG = (os.environ.get('DEBUGMODE') != 'False')


ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS').split(' ')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'auth_app',
    'main',
    'forming_kl',
    'foaming_kl',
    'forming_kr',
    'foaming_kr',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('POSTGRES_ENGINE'),
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_DB_HOST'),
        'PORT': os.environ.get('POSTGRES_DB_PORT'),
    },
    'forming_db_kl': {
        'ENGINE': os.environ.get('MSSQL_ENGINE'),
        'NAME': os.environ.get('MSSQL_KL_DB_FORMING'),
        'USER': os.environ.get('MSSQL_KL_USER'),
        'PASSWORD': os.environ.get('MSSQL_KL_PASSWORD'),
        'HOST': os.environ.get('MSSQL_KL_DB_HOST'),
        'PORT': os.environ.get('MSSQL_KL_DB_PORT'),
        'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server", },
    },
    'foaming_db_kl': {
        'ENGINE': os.environ.get('MSSQL_ENGINE'),
        'NAME': os.environ.get('MSSQL_KL_DB_FOAMING'),
        'USER': os.environ.get('MSSQL_KL_USER'),
        'PASSWORD': os.environ.get('MSSQL_KL_PASSWORD'),
        'HOST': os.environ.get('MSSQL_KL_DB_HOST'),
        'PORT': os.environ.get('MSSQL_KL_DB_PORT'),
        'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server", },
    },
    'forming_db_kr': {
        'ENGINE': os.environ.get('MSSQL_ENGINE'),
        'NAME': os.environ.get('MSSQL_KR_DB_FORMING'),
        'USER': os.environ.get('MSSQL_KR_USER'),
        'PASSWORD': os.environ.get('MSSQL_KR_PASSWORD'),
        'HOST': os.environ.get('MSSQL_KR_DB_HOST'),
        'PORT': os.environ.get('MSSQL_KR_DB_PORT'),
        'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server", },
    },
    'foaming_db_kr': {
        'ENGINE': os.environ.get('MSSQL_ENGINE'),
        'NAME': os.environ.get('MSSQL_KR_DB_FOAMING'),
        'USER': os.environ.get('MSSQL_KR_USER'),
        'PASSWORD': os.environ.get('MSSQL_KR_PASSWORD'),
        'HOST': os.environ.get('MSSQL_KR_DB_HOST'),
        'PORT': os.environ.get('MSSQL_KR_DB_PORT'),
        'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server", },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EET'

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'project/static/'), ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Routers for DB
# https://docs.djangoproject.com/en/4.1/topics/db/multi-db/

DATABASE_ROUTERS = ['project.dbrouters.EurobudDbRouter']


# Session expiry time

SESSION_COOKIE_AGE = 28800          # 8 hour age, "1209600(2 weeks)" by default
SESSION_SAVE_EVERY_REQUEST = True   # "False" by default


# Default login pagegit
# https://docs.djangoproject.com/en/4.2/ref/settings/#login-url

LOGIN_URL = 'auth_app:login_page'


# Add allowed bootstrap use in templates
# https://django-crispy-forms.readthedocs.io/en/latest/install.html
# https://github.com/django-crispy-forms/crispy-bootstrap5

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
