# Generated by Django 4.1.8 on 2023-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('loadfile', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='LoadFile', max_length=25)),
                ('productionline', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='ProductionLine', max_length=15)),
                ('ordernumber', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='OrderNumber', max_length=15, primary_key=True, serialize=False)),
                ('loadfiletime', models.DateTimeField(db_column='LoadFileTime')),
                ('datetimestart', models.DateTimeField(db_column='DateTimeStart')),
                ('datetimestop', models.DateTimeField(db_column='DateTimeStop')),
                ('r_mpurecipe', models.IntegerField(db_column='R_MpuRecipe')),
                ('r_recipenumber', models.IntegerField(db_column='R_RecipeNumber')),
                ('r_manufacturer', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='R_Manufacturer', max_length=15)),
                ('r_type', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='R_Type', max_length=15)),
                ('rawmatweightactual', models.FloatField(blank=True, db_column='RawMatWeightActual', null=True)),
                ('operator', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Operator', max_length=20, null=True)),
                ('comment', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Comment', max_length=10, null=True)),
            ],
            options={
                'db_table': 'General',
            },
        ),
    ]
