# Generated by Django 4.1.8 on 2023-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockstorage',
            fields=[
                ('numer', models.IntegerField(blank=True, db_column='Numer', null=True)),
                ('masa', models.FloatField(db_column='Masa')),
                ('operator', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Operator', max_length=10, null=True)),
                ('dataczasprodukcji', models.DateTimeField(db_column='DataCzasProdukcji', primary_key=True, serialize=False)),
                ('kodkreskowy', models.CharField(db_collation='Polish_CI_AS', db_column='KodKreskowy', max_length=27)),
                ('typbloku', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='TypBloku', max_length=7, null=True)),
                ('regranulat', models.SmallIntegerField(blank=True, db_column='Regranulat', null=True)),
                ('status', models.CharField(db_collation='Polish_CI_AS', db_column='Status', max_length=11)),
                ('czassezonowania', models.SmallIntegerField(db_column='CzasSezonowania')),
                ('dataczasciecia', models.DateTimeField(blank=True, db_column='DataCzasCiecia', null=True)),
                ('czasodciecia', models.SmallIntegerField(blank=True, db_column='CzasOdCiecia', null=True)),
                ('przerwa', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Przerwa', max_length=8, null=True)),
                ('sposoby', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Sposoby', max_length=11, null=True)),
                ('pvac1', models.SmallIntegerField(blank=True, db_column='Pvac1', null=True)),
                ('pvac2', models.SmallIntegerField(blank=True, db_column='Pvac2', null=True)),
                ('pp1', models.SmallIntegerField(blank=True, db_column='Pp1', null=True)),
                ('pp2', models.SmallIntegerField(blank=True, db_column='Pp2', null=True)),
                ('pp3', models.SmallIntegerField(blank=True, db_column='Pp3', null=True)),
                ('pp4', models.SmallIntegerField(blank=True, db_column='Pp4', null=True)),
                ('czvac1', models.SmallIntegerField(blank=True, db_column='CzVac1', null=True)),
                ('czvac2', models.SmallIntegerField(blank=True, db_column='CzVac2', null=True)),
                ('czp1', models.SmallIntegerField(blank=True, db_column='CzP1', null=True)),
                ('czp2', models.SmallIntegerField(blank=True, db_column='CzP2', null=True)),
                ('czp3', models.SmallIntegerField(blank=True, db_column='CzP3', null=True)),
                ('czp4', models.SmallIntegerField(blank=True, db_column='CzP4', null=True)),
            ],
            options={
                'db_table': 'BlockStorage',
            },
        ),
    ]
